version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  cs:
    depends_on:
      - db
    build:
      dockerfile: cs.Dockerfile
    ports:
      - "8088:8088"
  cc:
    depends_on:
      - cs
    build:
      dockerfile: cc.Dockerfile
    ports:
      - "8087:80"