CREATE TABLE category
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    allow_discrete BOOLEAN,
    marker_type   VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

