
CREATE TABLE nutzer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255),
    firstname   VARCHAR(255),
    lastname    VARCHAR(255),
    email       VARCHAR(255),
    password    VARCHAR(255),
    CONSTRAINT pk_nutzer PRIMARY KEY (id)
);

CREATE TABLE role
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE nutzer_roles (
                              role_id BIGINT,
                              nutzer_id BIGINT,
                              PRIMARY KEY (role_id, nutzer_id),
                              FOREIGN KEY (role_id) REFERENCES role (id),
                              FOREIGN KEY (nutzer_id) REFERENCES nutzer (id)
);