spring:
  datasource:
    url: jdbc:h2:file:./database/dbh2
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
server:
  port: 5123