CREATE TABLE category
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    allow_discrete BOOLEAN,
    CONSTRAINT pk_category PRIMARY KEY (id)
);
