spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: admin
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
server:
  port: 8088