spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cityguard
    username: admin
    password: pass
  jpa:
    generate-ddl: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8088